/**
 * Explanation layer.
 *
 * Planning decides what to read and locks the execution facts. This layer only
 * turns those facts into learner-facing teaching content. The workflow builds
 * every input below with deterministic code; an explanation Agent must never
 * add, remove, reorder, or resize route modules and blocks.
 */

import type {
  CodeNodeId,
  EvidenceId,
  RouteBlockId,
  RouteModuleId,
  SnapshotId,
  SourceRange,
} from './common';

/** One isolated explanation job. A fresh Agent context handles one module. */
export interface ModuleExplanationInput {
  schema_version: '1';
  route_plan_id: string;
  /** Rejects an explanation if the locked plan changed while it was generated. */
  decision_digest: string;
  snapshot_id: SnapshotId;

  /** Compact, read-only projection of the complete locked route. */
  route_outline: ExplanationRouteOutline;
  /** Full source and evidence only for the module being explained. */
  current_module: ExplanationModuleContext;

  /**
   * Relations owned by this job. The successful result must explain each ID
   * exactly once and must not explain any other relation.
   */
  relation_ids_to_explain: string[];
}

/** The route-wide context needed to understand where the current module sits. */
export interface ExplanationRouteOutline {
  goal: ExplanationRouteGoal;
  modules: ExplanationModuleOutline[];
  relations: ExplanationRouteRelation[];
  current_module_id: RouteModuleId;
}

/** Concrete scenario selected and locked by route planning. */
export interface ExplanationRouteGoal {
  title: string;
  scenario: string;
  observable_result: string;
  reason: string;
}

/**
 * Compact module catalogue. The objective and reason are copied from planning;
 * they are not summaries newly written for the explanation stage.
 */
export interface ExplanationModuleOutline {
  id: RouteModuleId;
  order: number;
  title: string;
  objective: string;
  reason: string;
  blocks: ExplanationBlockOutline[];
}

/** Enough block information to understand the whole route without other source. */
export interface ExplanationBlockOutline {
  id: RouteBlockId;
  module_id: RouteModuleId;
  order: number;
  route_order: number;
  title: string;
  /** Planning-stage reason for keeping this block on the selected route. */
  route_role: string;
  symbol_id: CodeNodeId;
  symbol: string;
  kind: string;
  location: SourceRange;
  focus_ranges?: ExplanationFocusRange[];
}

export interface ExplanationFocusRange {
  location: SourceRange;
  label?: string;
}

/** Real control-flow meaning; crossing a module boundary is recorded separately. */
export type ExplanationRelationType = 'calls' | 'returns' | 'continues' | 'callback';

/**
 * A validated execution fact projected from the locked route. planning_note is
 * internal context; it must be rewritten rather than copied as learner prose.
 */
export interface ExplanationRouteRelation {
  id: string;
  type: ExplanationRelationType;
  from_block_id: RouteBlockId;
  to_block_id: RouteBlockId;
  crosses_module_boundary: boolean;
  call_site?: ExplanationRelationSite;
  resume_site?: ExplanationRelationSite;
  condition?: string;
  planning_note: string;
  evidence_refs: EvidenceId[];
}

/** A source location already checked by the planning workflow. */
export interface ExplanationRelationSite {
  location: SourceRange;
  callee?: string;
  /** Exact source line copied by deterministic code, not generated by the Agent. */
  source_line?: string;
}

/** Full source packet for the one module this Agent is allowed to explain. */
export interface ExplanationModuleContext {
  module_id: RouteModuleId;
  blocks: ExplanationBlockSource[];
  /** Evidence excerpts for relations touching this module, including bridge code. */
  relation_evidence: ExplanationRelationEvidence[];
}

export interface ExplanationBlockSource {
  block_id: RouteBlockId;
  content_digest: string;
  /** Complete locked block with every line prefixed by its real source line number. */
  numbered_source: string;
}

export interface ExplanationRelationEvidence {
  relation_id: string;
  excerpts: ExplanationSourceExcerpt[];
}

export interface ExplanationSourceExcerpt {
  location: SourceRange;
  content_digest: string;
  /** Exact source text resolved from evidence referenced by the locked relation. */
  numbered_source: string;
}

/** An explanation either succeeds completely or reports a route problem. */
export type ModuleExplanationResult = ModuleExplanationReady | ModuleExplanationRouteIssue;

export interface ModuleExplanationReady extends ModuleExplanationResultBase {
  status: 'ready';
  module: ModuleTeachingExplanation;
  /** Exactly one item for every block in current_module, in locked order. */
  blocks: BlockTeachingExplanation[];
  /** Exactly the relations listed in relation_ids_to_explain. */
  relations: RelationTeachingExplanation[];
}

interface ModuleExplanationResultBase {
  schema_version: '1';
  route_plan_id: string;
  decision_digest: string;
  snapshot_id: SnapshotId;
  module_id: RouteModuleId;
}

/** Learner-facing orientation shown before the module's code blocks. */
export interface ModuleTeachingExplanation {
  summary: string;
  why_read: string;
  expected_input: string;
  expected_outcome: string;
  takeaway: string;
}

/** All teaching content owned by one locked block. */
export interface BlockTeachingExplanation {
  block_id: RouteBlockId;
  /** What this code does in the selected scenario. */
  summary: string;
  /** Why the learner needs this block now and how it connects to nearby blocks. */
  why_read: string;
  /** Ordered key regions inside the block; a short function may use one region. */
  walkthrough: ExplanationWalkthroughSection[];
  /** One to three conclusions the learner should retain. */
  takeaways: string[];
  /** Present only when a long complete block contains irrelevant branches. */
  skip_guidance?: ExplanationSkipGuidance[];
  /** Present only when dense control flow is clearer as pseudocode. */
  pseudocode?: string;
}

/** The file is implied by block_id; line numbers must stay inside that block. */
export interface ExplanationWalkthroughSection {
  title: string;
  start_line: number;
  end_line: number;
  explanation: string;
}

/** Lines that remain visible but need not be studied for this concrete scenario. */
export interface ExplanationSkipGuidance {
  start_line: number;
  end_line: number;
  reason: string;
}

/** Learner wording for one already-locked relation fact. */
export interface RelationTeachingExplanation {
  relation_id: string;
  explanation: string;
}

/**
 * Returned instead of partial teaching content when the locked route cannot be
 * explained from the supplied source. The Agent reports evidence but no repair;
 * route review decides whether a local planning revision is needed.
 */
export interface ModuleExplanationRouteIssue extends ModuleExplanationResultBase {
  status: 'route_issue';
  issues: ExplanationRouteIssue[];
}

export type ExplanationRouteIssueCode =
  | 'missing_implementation'
  | 'unsupported_relation'
  | 'incorrect_order'
  | 'scenario_mismatch'
  | 'source_mismatch'
  | 'invalid_module_boundary';

export interface ExplanationRouteIssue {
  code: ExplanationRouteIssueCode;
  summary: string;
  affected_block_ids: RouteBlockId[];
  affected_relation_ids: string[];
  evidence: ExplanationIssueEvidence[];
}

export interface ExplanationIssueEvidence {
  block_id?: RouteBlockId;
  relation_id?: string;
  location?: SourceRange;
  observation: string;
}

/** Digest of one exact source block used by the explanation workflow. */
export interface ExplanationSourceManifestEntry {
  module_id: RouteModuleId;
  block_id: RouteBlockId;
  content_digest: string;
}

/** Digest of a module's complete deterministic input, including relation evidence. */
export interface ExplanationInputManifestEntry {
  module_id: RouteModuleId;
  input_digest: string;
}

/** Complete explanation-stage output consumed directly by delivery publication. */
export interface RouteExplanationReady {
  status: 'ready';
  route_plan_id: string;
  decision_digest: string;
  modules: ModuleExplanationReady[];
  source_manifest: ExplanationSourceManifestEntry[];
  input_manifest: ExplanationInputManifestEntry[];
}

/** Stops publication while preserving completed module work for a local repair. */
export interface RouteExplanationIssue {
  status: 'route_issue';
  route_plan_id: string;
  decision_digest: string;
  modules: ModuleExplanationResult[];
  source_manifest: ExplanationSourceManifestEntry[];
  input_manifest: ExplanationInputManifestEntry[];
  issues: ExplanationRouteIssue[];
}

export type RouteExplanationResult = RouteExplanationReady | RouteExplanationIssue;
